apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-github-repository
  title: GH Repo Creation Template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: platform
  type: service

  parameters:
    - title: Fill in the service details
      properties:
        cluster_name:
          title: cluster_name
          type: string
          enum:
            - cap
            - courier         
            - data            
            - fintech         
            - growth          
            - it-security     
            - mlp
            - paf
            - sectech         
            - web
            - contact         
            - customer        
            - finance         
            - food-innovation gx
            - logistics       
            - mobile          
            - platform   
          enumNames:
            - cap
            - courier         
            - data            
            - fintech         
            - growth          
            - it-security     
            - mlp
            - paf
            - sectech         
            - web
            - contact         
            - customer        
            - finance         
            - food-innovation gx
            - logistics       
            - mobile          
            - platform 
          ui:autofocus: true
        repo_name:
          title: Service Repository Name
          type: string
          ui:field: EntityNamePicker
          ui:autofocus: true
        github_team:
          title: GH team
          type: string
          description: GH team
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
          ui:autofocus: true
        db_reviewers:
          title: DB Reviewers
          type: boolean
          ui:widget: radio
          ui:autofocus: true
        prod_enabled:
          title: Prod Enabled
          type: boolean
          ui:widget: radio
          ui:autofocus: true
        stage_enabled:
          title: Stage Enabled
          type: boolean
          ui:widget: radio
          ui:autofocus: true
        spinnaker_webhook:
          title: Spinnaker Webhook
          type: boolean
          ui:widget: radio
          ui:autofocus: true
        jenkins_webhook:
          title: Jenkins Webhook
          type: boolean
          ui:widget: radio
          ui:autofocus: true
        project_description:
          title: Description
          type: string
          description: Description of the project
          ui:field: EntityNamePicker
          ui:autofocus: true

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./prod
        cookiecutterCompat: true
        values:
          cluster_name: ${{parameters.cluster_name}}
          repo_name: ${{parameters.repo_name}}
          github_team: ${{parameters.github_team}}
          db_reviewers: ${{parameters.db_reviewers}}
          prod_enabled: ${{parameters.prod_enabled}}
          stage_enabled: ${{parameters.stage_enabled}}
          spinnaker_webhook: ${{parameters.spinnaker_webhook}}
          jenkins_webhook: ${{parameters.jenkins_webhook}}
          project_description: ${{parameters.project_description}}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: github.com?repo=software-templates&owner=bitan
        title: "Create new project: ${{parameters.repo_name}}"
        branchName: create-${{parameters.repo_name}}
        description: |
          ${{ parameters.project_description if parameters.project_description }}
        targetPath: ./prod

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"
