apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: GH Repo Creation template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      properties:
        cluster_name:
          title: cluster_name
          type: string
          description: Cluster name
        repo_name:
          title: repo_name
          type: string
          description: Repo name
        github_team:
          title: GH team
          type: string
          description: GH team
        db_reviewers:
          title: DB reviewers
          type: string
          description: DB reviewers
        prod_enabled:
          title: Prod enabled
          type: string
          description: Prod enabled
        stage_enabled:
          title: stage enabled
          type: string
          description: Stage enabled
        spinnaker_webhook:
          title: Spinnaker webhook
          type: string
          description: Spinnaker webhook
        jenkins_webhook:
          title: jenkins webhook
          type: string
          description: Jenkins webhook
        project_description:
          title: Description
          type: string
          description: Description of the project

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      cookiecutterCompat: true
      input:
        url: ./prod
      values:
          cluster_name: ${{parameters.cluster_name}}
          repo_name: ${{parameters.repo_name}}
          github_team: ${{parameters.github_team}}
          db_reviewers: ${{parameters.db_reviewers}}
          prod_enabled: ${{parameters.prod_enabled}}
          stage_enabled: ${{parameters.stage_enabled}}
          spinnaker_webhook: ${{parameters.spinnaker_webhook}}
          jenkins_webhook: ${{parameters.jenkins_webhook}}
          project_description: ${{parameters.project_description}}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: "Glovo/terraform-github-repository"
        title: "Create new project: ${{parameters.repo_name}}"
        branchName: create-${{parameters.repo_name}}
        description: |
          ${{ parameters.project_description if parameters.project_description }}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"
